debug-mode: true

commands: # command permissions in permissions.yml
  fly:
    worlds: # can be set to single string saying either "banned_overall" or "allowed_overall"
      - "Lobby"
      - "Steading"
      - "Steading_nether"
      - "Steading_the_end"
    aliases:
      - flight
    usage-message: "&7/fly [player]"
    messages:
      fly-on-message: "&7Fly mode has been set to &atrue"
      fly-off-message: "&7Fly mode has been set to &cfalse"
      fly-on-other-message: "&7Fly mode has been set to &atrue &7for &e%player%"
      fly-off-other-message: "&7Fly mode has been set to &cfalse &7for &e%player%"
